### ISSUE TITLE
[Apio 0.1.6.4] The comand "apio examples -l" gives different outputs in windows than in Linux

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#114]
I am testing Apio 0.1.6.4

When this command is issued:

```
$ apio examples -l
```
what is shown in windows 7 is:

![screenshot from 2016-09-30 15-50-02](https://cloud.githubusercontent.com/assets/1286062/18994169/d993ddba-8726-11e6-985a-46783d7969e9.png)

Instead of the names, you see the full path

But in Linux, what is shown are the names of the examples (not the paths):

![screenshot from 2016-09-30 15-50-48](https://cloud.githubusercontent.com/assets/1286062/18994179/e97e7276-8726-11e6-8a34-3d7477884d25.png)

I am not sure if this is a bug in apio for windows. I think that the output should be similar in both systems

**Comment by Jesus89** [comment]
Execute `apio install -l`.

You have different versions of _examples_ package.

`apio install examples` will do the job.

Also, I will check this for windows. It should appear _icezum/leds_ instead of the full path.

**Comment by Obijuan** [comment]
I can confirm that this bug is fixed. I've tested it on Windows 7 virtual machine. Everything was ok
