### ISSUE TITLE
Problems with scons

### ISSUE THREAD

**Issue by JJ** [FPGAwars/apio#125]
When I use "verify" o "build" or anything that uses scons, I get

~~~
➜  leds git:(master) ✗ apio build
Info: use apio.ini board: icezum
Using default SConstruct file
[Tue Nov 29 10:03:32 2016] Processing icezum
--------------------------------------------------------------------------------
scons: *** SCons version 2.4.1 does not run under Python version 3.5.2.
Python 3 is not yet supported.
~~~

In fact, it's not using the system-wide Scons, which is upgraded to 2.5.1, supposed to work with Python3. I have edited apio and simply changed it to "python" instead of Python3 and it does not work.

**Comment by JJ** [comment]
OK, I got it. Please make sure that the `pip` that is installed and called by default is the one for version 2. I have used it and re-installed apio and it works.

**Comment by Jesus89** [comment]
Hi. Scons is not supported yet in Python 3. We hope to have soon this release to have a fully Pytho3-compatible apio tool.
