### ISSUE TITLE
libffi not found

### ISSUE THREAD

**Issue by sonium0** [FPGAwars/apio#126]
libffi is not installed by default on MacOS Sierra:
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
Referenced from: /Users/sonium/.apio/packages/toolchain-icestorm/bin/yosys
Reason: image not found
scons: *** [hardware.blif] Error -6

This can however be fixed easily by 'brew install libffi'.

**Comment by Jesus89** [comment]
Thanks. This was fixed in Icestudio (https://github.com/FPGAwars/icestudio/commit/a24577a743967fb12b481a5c00800e74ffb4b527) but not in apio.
