### ISSUE TITLE
Add support to the Mystorm Blackice board

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#131]
Main issue for giving support to the mystorm blackice open fpga board. This issue will be break down into smaller issues. This issue will be closed when the initial support is working ok

Roadmap
--------

* Add the blakice in the list of board, so that the build can be done with apio build command (and the .ini apio file)
* Create a python tool for downloading into the board (similar to cat > /dev/ttyUSB). This tool should be multiplatform (Windows, mac, linux). black-iceprog? (a name is needed)
* Include support for auto-detecting the blackice board serial port. I think this is the most difficult part
* Include the blackiceprog toolchain as part of apio (install, uninstall, etc...)
* Create a new scons file that calls blackiceprog instead of iceprog when the blackice board is used
* Implement the apio upload command for the blackice
* Include some examples: blackice/leds, etc...

**Comment by jpenalbae** [comment]
After PR #135 the only missing things are examples which I will probably do during next weekend. And maybe creating a package for the the `black-iceprog.py` script and upload it to pypi to be able to set it as dependency.

**Comment by tinyfpga** [comment]
@jpenalbae, @Obijuan : I added a basic template example in my pull request for apio-examples: https://github.com/FPGAwars/apio-examples/pull/9

**Comment by Obijuan** [comment]
Thanks a lot! This is great!  @Jesus89 and I will test it before closing the issue

**Comment by Jesus89** [comment]
Closed by: https://github.com/FPGAwars/apio/pull/139
