### ISSUE TITLE
Fully migration of apio to python3

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#145]
Apio works with python3 excepts for the tinyFPGA board

- [x] Migration of [tinyfpga programmer](https://github.com/tinyfpga/TinyFPGA-B-Series/tree/master/programmer) to python3 ([Issue at tinyfpga](https://github.com/tinyfpga/TinyFPGA-B-Series/issues/13))
- [x] Testing and checking that apio works ok in python3

**Comment by Obijuan** [comment]
I have an initial version of tinyfpga programmer in python3 in my fork (branch python3). I've already emitted a pull-request, but I would be great if anyone can try it

https://github.com/Obijuan/TinyFPGA-B-Series/tree/python3

**Comment by Jesus89** [comment]
Done in release [0.3.2](https://github.com/FPGAwars/apio/releases/tag/0.3.2)
