### ISSUE TITLE
External Toolchain is not recognized

### ISSUE THREAD

**Issue by martin2250** [FPGAwars/apio#173]
Both icestorm and scons are installed on my system (Archlinux), but apio still prompts me to install them using the internal package manager:
```
$which icepack
/usr/bin/icepack
$which scons
/usr/bin/scons
$apio build
Error: scons toolchain is not installed
Please run:
   apio install scons
Error: icestorm toolchain is not installed
Please run:
   apio install icestorm
```
Does apio require specific versions of these packages? If not, apio should check for the availability of the needed commands instead of checking against the internal package manager.

**Comment by Jesus89** [comment]
Yes, It requires specific versions of the packages. In this case:
- https://github.com/FPGAwars/tool-scons
- https://github.com/FPGAwars/toolchain-icestorm

However, I'll revisit it to make it more flexible in case you have the packages already installed in your system.

**Comment by Obijuan** [comment]
Scons is no longer an internal apio package. It is installed as an apio dependecy
