### ISSUE TITLE
Use new FPGA toolchain

### ISSUE THREAD

**Issue by Jesus89** [FPGAwars/apio#184]
Replace `icestorm` -> `yosys`, `ice40`, `ecp5` (already on develop)

Check and release Apio 0.5.0 (and Icestudio 0.5)

**Comment by folknology** [comment]
Does this include nextpnr?

**Comment by Obijuan** [comment]
Yes, the current develop branch include the nextpnr. It would be great if you could test it @folknology

**Comment by Obijuan** [comment]
I will close this issue, as it is already implemented on the develop branch
