### ISSUE TITLE
Add support for BlackIceMx/IceCore

### ISSUE THREAD

**Issue by folknology** [FPGAwars/apio#185]
This probably won't need much, a new PCF is the main thing AFAIK as the programming is backward compatible with BlackIce II. One new feature is flash programming support, however this operates like normal programming except one changes the board mode via the mode button. Not sure exactly what I need to provide in order to make the changes?

**Comment by Obijuan** [comment]
Support for the BlackIceMx board was already done in this PR:

https://github.com/FPGAwars/apio/pull/187

It was merged in apio 0.4.1

Feel free to open a new issue if you find problems with it

During these holidays we will give some time to apio.  Sorry for the late response :-(
