### ISSUE TITLE
Loading libftdi1.2.dylib

### ISSUE THREAD

**Issue by Pa0rba** [FPGAwars/apio#189]
Hi,

Using the blink.v program for my Upduino 2, attempting to upload the bitstream to the board using "apio upload" on mac terminal. I get the error :

dyld: Library not loaded: /usr/local/opt/libftdi/lib/libftdi1.2.dylib
Referenced from: /Users/baba/.apio/packages/tools-system/bin/lsftdi
Reason: image not found

**Comment by trylaarsdam** [comment]
Were you able to solve this issue? Having the same error when trying `apio system --lsftdi`

**Comment by Obijuan** [comment]
I will keep issue open until more people can test it  (When we finish the release of icestudio 0.8 we will start a new cycle and we will continue with the process of updating the toolchains/solving issues)

**Comment by trylaarsdam** [comment]
<img width="228" alt="Screen Shot 2021-12-08 at 2 02 06 PM" src="https://user-images.githubusercontent.com/50586094/145276609-4cba027a-f59c-4c98-b4d4-c99cd1d56fbc.png">
To add to this, the error also occurs in the latest version of icestudio on an M1 macbook running big sur.

**Comment by Obijuan** [comment]
This error should have been fixed in apio 0.8.1. Please try it and feel free to re-open this issue if it remains (or open a new issue if a new bug is found). Thanks for the feedback
