### ISSUE TITLE
Not an issue, Can you add Papilio one board from gadget factory to this IDE please

### ISSUE THREAD

**Issue by vaidhyamookiah** [FPGAwars/apio#197]
Hi,

Many of us have open source papilio board, if you could add complier for that board it would be useful and i can help others learn FPGA easily.
Thanks in advance.
[https://papilio.cc/index.php?n=Papilio.Hardware]

**Comment by Obijuan** [comment]
I am afraid that it is not going to be possible currently. That board uses a propietary FPGA. There are no open source toolchains for generating the bitstream for that FPGA. You can only use the toolchain provided by the manufacturer.

There are people in the community working on supporting that FPGA, but it will take time...

Have a look at the symbiflow project for more information

https://symbiflow.github.io/

I will close this issue
