### ISSUE TITLE
Upload to OrangeCrab v0.2.1 doesn't work

### ISSUE THREAD

**Issue by luizribeiro** [FPGAwars/apio#239]
I'm getting this error when trying to upload a simple example to an OrangeCrab board:

```
% apio upload -v
(DEBUG) Profile path: /Users/luiz/.apio/profile.json
(DEBUG) Home_dir: /Users/luiz/.apio
(DEBUG) Profile path: /Users/luiz/.apio/profile.json
(DEBUG) Home_dir: /Users/luiz/.apio
Error: 'NoneType' object has no attribute 'get'
(DEBUG) Profile path: /Users/luiz/.apio/profile.json
(DEBUG) Home_dir: /Users/luiz/.apio
```

When I upload directly using `dfu-util -d 1209:5af0 -D hardware.bit` everything works fine.

See https://github.com/luizribeiro/fpga-sandbox/tree/main/orangecrab-blink for the full example.

Is there any way to enable the full stack trace on that error so I can help debug?

**Comment by Obijuan** [comment]
This has been fixed in the new apio 0.8.1 release. Please try it and feel free to reopen it if the problem remains
