### ISSUE TITLE
Unable to upload to board - 'PosixPath' object is not iterable

### ISSUE THREAD

**Issue by AlienTux** [FPGAwars/apio#243]
I'm trying to upload a very simple code to my TinyFPGA BX and I'm getting this error:

```
kurt@kurt-lin ~/Documents/googleDriveUVG/2021-02/00-digital-1/06-fpga-tests/apio_template - copia $ apio upload
(DEBUG) Profile path: /home/kurt/.apio/profile.json
(DEBUG) Home_dir: /home/kurt/.apio
(DEBUG) Profile path: /home/kurt/.apio/profile.json
(DEBUG) Home_dir: /home/kurt/.apio
(DEBUG) Run Command: lsusb
(DEBUG) System_base_dir: /home/kurt/.apio/packages/tools-oss-cad-suite
(DEBUG) System bin dir: /home/kurt/.apio/packages/tools-oss-cad-suite/bin
(DEBUG) Executable file: /home/kurt/.apio/packages/tools-oss-cad-suite/bin/lsusb
'PosixPath' object is not iterable
```

I had the same error in Icestudio (and also made a bug report in that repo), but I believe the problem is in Apio?

Using Solus 4.3 atm. Can provide any logs or info necessary to fix the issue.

Thank you!

**Comment by Obijuan** [comment]
This bug is fixed in the version 0.8.1. Please try it and feel free to reopen this issue in case it remains, or create a new issue if new errors are detected
Thanks for the feedback
