### ISSUE TITLE
Missing iCESugar nano board due to someone commit.

### ISSUE THREAD

**Issue by TiNredmc** [FPGAwars/apio#255]
Hello, recently I just working on Icestudio support for iCESugar nano. I first though that Apio doesn't support iCESugar nano (iCE40LP1K) yet. but it's turn out that someone already pulled request but the commit  [`f1d0ed61bf27924da11d32e085865e86abb15c05`](https://github.com/FPGAwars/apio/commit/f1d0ed61bf27924da11d32e085865e86abb15c05) (probably) mistakenly replace iCESugar nano with other board.

**Comment by benitoss** [comment]
solved in the 
commit b3f1ff872154533aa89c5a833d82848d01eae0fc

Sorry

**Comment by TiNredmc** [comment]
> solved in the 
> commit b3f1ff872154533aa89c5a833d82848d01eae0fc
> 
> Sorry 
> 

Thank you :D

**Comment by Obijuan** [comment]
Thanks Fernando! 😃️
