### ISSUE TITLE
[board request] APIO support for the iceWerx Board

### ISSUE THREAD

**Issue by ertgtct** [FPGAwars/apio#286]
It would be graet to have support for this low cost FPGA Board:
https://www.robotshop.com/en/devantech-icewerx-ice40-hx8k-fpga.html
It should be feasable, because it uses the ice40hx8k and is programmed with the iceFun programmer.
Thanks!

**Comment by Obijuan** [comment]
Yes, it is feasable. I did not know this board. I will buy one and add support to it (I can't tell you how much time it will take as I have very little time). But I will add to my todo-list

Thanks for the suggestion

**Comment by Obijuan** [comment]
I have just received my iceWerx board. Support in apio and icestudio are coming 😀️

**Comment by Obijuan** [comment]
The board is already supported. It was easy to add to apio because it is very similar to the iceFun board, that was already supported.
I will close this issue once the board is fully suported in Icestudio

**Comment by Obijuan** [comment]
Support in Icestudio is ready!  Icestudio 0.9.2w202205020905 or higher
