### ISSUE TITLE
(tools-oss-cad-suite 0.0.7) apio sim ko iverlio + vvp error failed to open libbz2.so.1.0

### ISSUE THREAD

**Issue by r1mk** [FPGAwars/apio#289]
Hi, 

I ran into an issue using the command `apio sim` on my linux (fedora 31 64b, python 3.8.10 libbz2 1.0.8): 
```
libbz2.so.1.0: cannot open shared object file: No such file or directory
```

Steps to reproduce:
- install apio with pip: `pip install -U --user apio` (version: 0.8.0)
- install ice40, examples, iverilog and oss-cad-suite with `apio install ...` (oss-cad-suite 0.0.7)
- deploy one example `apio examples -d iCE40-HX8K-EVB/leds`
- run the simulation `apio sim` for this example

result:
```
(...)
iverilog -B "/home/r1mk/.apio/packages/tools-oss-cad-suite/lib/ivl" -o leds_tb.out -D VCD_OUTPUT=leds_tb -D NO_ICE40_DEFAULT_ASSIGNMENTS /home/r1mk/.apio/packages/tools-oss-cad-suite/share/yosys/ice40/cells_sim.v leds.v leds_tb.v
error: Failed to open '/home/r1fed/.apio/packages/tools-oss-cad-suite/lib/ivl/system.vpi' because:
: libbz2.so.1.0: cannot open shared object file: No such file or directory
vvp -M "/home/r1mk/.apio/packages/tools-oss-cad-suite/lib/ivl" leds_tb.out
/home/r1mk/.apio/packages/tools-oss-cad-suite/lib/ivl/system.vpi:`/home/r1mk/.apio/packages/tools-oss-cad-suite/lib/ivl/system.vpi' failed to open using dlopen() because:
libbz2.so.1.0: cannot open shared object file: No such file or directory.
leds_tb.v:35: Error: System task/function $dumpfile() is not defined by any module.
(...)
```

on my box there is only libbz2.so, libbz2.so.1 and libbz2.so.1.0.8 in `/lib64/`

- adding a symbolic link `sudo ln -s /lib64/libbz2.so /lib64/libbz2.so.1.0` solve the first error message (iverilog) but `vvp` still fails with the same error.  
- adding a new symbolic link `sudo ln -s /lib64/libbz2.so /usr/lib/libbz2.so.1.0` solve the issue but this is really bad! (a 64b library in a 32b lib directory)

A better solution is to replace the content of`.apio/packages/tools-oss-cad-suite` by the content of the last available release for x86_64 systems [link to the tgz archive](https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-02-24/oss-cad-suite-linux-x64-20220224.tgz).  

By doing there is no need to create symbolic links anymore: iverilog and vvp will use the libbz2.so installed and everything goes well.  

By the way, oss-cad-suite brings iverilog and vvp but apio complains if we don't install explicitely iverilog with `apio install iverilog`.

**Comment by Obijuan** [comment]
Thanks for you feedback. The libbz2 has been included in the lates oss-cad-suite apio package (0.0.8). You should not the error. Please, reopen the issue it if has not been fully fixed
