### ISSUE TITLE
apio/blob/develop/apio/managers/scons.py: get_terminal_size removed in click 8.1.0

### ISSUE THREAD

**Issue by rd235** [FPGAwars/apio#290]
scons.py fails if click 8.1.0 is used.

see: https://github.com/pallets/click/blob/main/CHANGES.rst
There was a warning in the previous version of click:
deprecated:: 8.0
Will be removed in Click 8.1. Use :func:`shutil.get_terminal_size` instead.

The proposed patch follows:
```
---------------------------------------------
18a19
> import shutil
483c484
<         terminal_width, _ = click.get_terminal_size()
---
>         terminal_width, _ = shutil.get_terminal_size()
----------------------------------------------
```

**Comment by Obijuan** [comment]
Thanks for you help 🙂️
