### ISSUE TITLE
Documentation incomplete for adding new boards

### ISSUE THREAD

**Issue by mkvenkit** [FPGAwars/apio#299]
The documentation for adding a new board to apio seems incomplete:

https://github.com/FPGAwars/apio/wiki/Adding-new-boards-to-apio

Please add some details. 

Thanks!

**Comment by cavearr** [comment]
Hi @mkvenkit ! what type of programmer do you use? ftdi? jtag? Have you any documentation about your board?

**Comment by mahesh-electronut** [comment]
Hi @cavearr thanks for your response. The RP2040 on the board acts as a programmer. Here's a guide to getting started with board. The board is not released yet, so I am still working on documentation and firmware:

https://github.com/mkvenkit/humble_ice/blob/main/getting_started.md

This is the Python script used to upload the bitstream:

https://github.com/mkvenkit/humble_ice/blob/main/hiprog.py

**Comment by cavearr** [comment]
Thanks! mahesh, i think i could integrate without the needed to add to apio, because recently i integrate the badge for the mch2022 that uses the rp2040 as programmer like you. Give me some time to try and i'm telling you to check it.

One thing i need of you is the pcf file of your board.

**Comment by mahesh-electronut** [comment]
@cavearr the only constraints required are the clk signal and the LED. So a minimal PCF file is:

```
set_io clk 35
set_io LED 13
```

The rest can be set by the user as needed.

**Comment by cavearr** [comment]
Hi Mahesh! in Icestudio is needed to assign the input and output pins for the board, in the near future the user could modify easily from the interface but for now, the board should do the initial preset to provide at Icestudio the information to configure inputs and outputs 

If other pins in your board could be input/output, setup in this way in the pcf , but this, is needed. 


De: "Mahesh Venkitachalam" ***@***.***> 
Para: "FPGAwars/apio" ***@***.***> 
CC: "Carlos" ***@***.***>, "Mention" ***@***.***> 
Enviados: Jueves, 22 de Septiembre 2022 8:21:23 
Asunto: Re: [FPGAwars/apio] Documentation incomplete for adding new boards (Issue #299) 





[ https://github.com/cavearr | @cavearr ] the only constraints required are the clk signal and the LED. So a minimal PCF file is: 
set_io clk 35
set_io LED 13 


The rest can be set by the user as needed.

**Comment by mahesh-electronut** [comment]
OK, I will work on this and get back to you. Thanks

**Comment by Obijuan** [comment]
The documentation on how to add boards to apio has been added. It is located here: https://github.com/FPGAwars/apio/wiki/Adding-new-boards-to-apio
