### ISSUE TITLE
iCESugar-Pro board definition appears incorrect

### ISSUE THREAD

**Issue by ahaberlach** [FPGAwars/apio#312]
The iCESugar-Pro board definition appears to specify the incorrect part.

apio currently has it specified as ECP5-LFE5U-25F-CABGA381

The schematic at https://github.com/wuxx/icesugar-pro/tree/master/schematic specifies it as LFE5U-25F-6B-G256C

I was able to get it working with apio by changing my boards.json to ECP5-LFE5U-25F-CABGA256

**Comment by Obijuan** [comment]
Thanks! It would be great if you could pull-request it

**Comment by ahaberlach** [comment]
Ok, PR created -- I'm relatively new to the github workflow, and I don't seem to be able to assign the PR (or this issue), but I suspect you can merge or approve a merge.

**Comment by Obijuan** [comment]
Thanks for the PR. It would be great if you could test the development version (apio 0.8.2). For installing it use this command:

* **Linux** and **Mac**:

```
sudo pip3 install -U git+https://github.com/FPGAwars/apio.git@develop#egg=apio
```
* **Windows**:
```
pip3 install -U git+https://github.com/FPGAwars/apio.git@develop#egg=apio
```

**Comment by Xelef2000** [comment]
I tested the pr and building works without problems.
But I had problems with the upload.
The newer version of the iCESugar-Pro use geehy apm32 for the jtag interface.

**Comment by Obijuan** [comment]
@ahaberlach apio 0.8.2 has been released with your fix. Could you please check that your initial issue has been fixed?
