### ISSUE TITLE
Add example: Alchitry-Cu

### ISSUE THREAD

**Issue by mrholderfield** [FPGAwars/apio#324]
I have a turn on all leds example for the Alchitry-Cu (CB-132) board that I would like to contribute to the example set. It's the iCE40-HXHK/leds example but with updated pin assignment. I don't have permission to add the file so how do I?

**Comment by Obijuan** [comment]
You can find instructions on how to add more examples here:
https://github.com/FPGAwars/apio/wiki/The-apio-examples-package
