### ISSUE TITLE
WindowsPath object is not iterable error when running 'apio upload'

### ISSUE THREAD

**Issue by WheatleyOS** [FPGAwars/apio#338]
I'm completely new to apio but I can recreate the issue precisely. I'm running Windows 11 with Python 3.7.9 and trying to run apio with a Lattice icestick with an HX1K chip. I installed my board's drivers and set up apio with the following:
`pip install apio==0.8.4`
`apio install -p windows_amd64 --all` (if I don't force windows_amd64 I get issues with the oss-cad-suite package not installing, this may be a hint as to what's going on?)
`apio examples -d icestick\leds`
`cd .\icestick\leds\`
`rm apio.ini` (default apio.ini syntax is incompatible with apio 0.8.4)
`apio init -b icestick`
No issues so far. When I run `apio verify` the first weird thing happens. I get:

`(DEBUG) Profile path: C:\Users\user\.apio\profile.json`
`(DEBUG) Home_dir: C:\Users\user\.apio`

`PATH: C:\Users\user\.apio\packages\tools-oss-cad-suite\bin;C:\Users\user\.apio\packages\tools-oss-cad-suite\lib;C:\Users\user\.apio\packages\tool-gtkwave\bin;C:\Users\user\.apio\packages\tool-gtkwave\bin;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\Notepad++;C:\Users\user\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python37-32\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;`

`iverilog -o hardware.out -D VCD_OUTPUT= -D NO_ICE40_DEFAULT_ASSIGNMENTS "C:\Users\user\.apio\packages\tools-oss-cad-suite\share\yosys/ice40/cells_sim.v" leds.v`
`======================= [SUCCESS] Took 0.70 seconds =======================`

Not sure what the giant PATH string is about, but I haven't seen anyone else with this online... But anyways it says success.
Next, I run `apio sim` and `apio build` again with no issues other than the PATH string being included.
When I run `apio upload` I get the following error:

`(DEBUG) Profile path: C:\Users\user\.apio\profile.json`
`(DEBUG) Home_dir: C:\Users\user\.apio`
`(DEBUG) Profile path: C:\Users\user\.apio\profile.json`
`(DEBUG) Home_dir: C:\Users\user\.apio`
`(DEBUG) Run Command: lsusb`
`(DEBUG) System_base_dir: C:\Users\user\.apio\packages\tools-oss-cad-suite`
`(DEBUG) System bin dir: C:\Users\user\.apio\packages\tools-oss-cad-suite\bin`
`(DEBUG) Executable file: C:\Users\user\.apio\packages\tools-oss-cad-suite\bin\lsusb.exe`
`'WindowsPath' object is not iterable`

Beyond seeming to be related to PATH and oss-cad-suite I don't know what's going on here.

**Comment by Obijuan** [comment]
Lates stable version: 0.9.3
I think the bug is fixed. I am  closing this issue. Feel free to reopen it if the problem remains
