### ISSUE TITLE
Testing apio install pio-fpga in Windows

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#35]
Testing the pio install pio-fpga command from a native windows machine
Follow this installation instructions:

https://github.com/FPGAwars/Platformio-FPGA/wiki/Platformio-FPGA-wiki-home

It would be great to test it both in platformio cli and ide

**Comment by Jesus89** [comment]
![pio-windows](https://cloud.githubusercontent.com/assets/2227572/14633513/3abcc56e-061e-11e6-917d-079cbe818889.png)

Cli tests SUCCESS.

**Comment by Jesus89** [comment]
IDE tests SUCCESS

![pio-atom-windows](https://cloud.githubusercontent.com/assets/2227572/14633858/c919f380-061f-11e6-82a2-6f0fd44dfbd9.png)

**Comment by Obijuan** [comment]
Great! I've also tested it on a windows 64-bits virtual machine. It works!
