### ISSUE TITLE
Testing apio install pio-fpga in Mac

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#36]
Testing the pio install pio-fpga command from a native MAC machine
Follow this installation instructions:

https://github.com/FPGAwars/Platformio-FPGA/wiki/Platformio-FPGA-wiki-home

It would be great to test it both in platformio cli and ide

**Comment by Jesus89** [comment]
Done. All OK!

CLI

![captura de pantalla 2016-04-19 a las 11 42 56](https://cloud.githubusercontent.com/assets/2227572/14635148/6526e65c-0625-11e6-97e6-740f9d716650.png)

IDE

![captura de pantalla 2016-04-19 a las 11 51 26](https://cloud.githubusercontent.com/assets/2227572/14635155/69cf0a40-0625-11e6-8042-b5218da0a55e.png)

Simulation

![captura de pantalla 2016-04-19 a las 11 53 08](https://cloud.githubusercontent.com/assets/2227572/14635163/72182146-0625-11e6-9e1e-af6a8e75d06f.png)

**Comment by Obijuan** [comment]
Amazing!!!!!!!!!  :-)
