### ISSUE TITLE
Please create a FPGAwars/tools-graphviz repository.

### ISSUE THREAD

**Issue by zapta** [FPGAwars/apio#449]
@Obijuan, @cavearr, please create a ``FPGAWars/tools-graphviz`` repository for the graphviz package. You can copy the files and release from here https://github.com/zapta/tools-graphviz (but please just copy, do no fork, since my repo is temporary and will go away). 

I am working on having the ``gtkwave`` and ``dot`` commands being installed by apio packages on all three platforms (for ``apio sim``, and ``apio graph`` respectively).  The upstream oss-cad-tools packages already includes the graphviz tools for linux and darwin but not for windows. This package fills this gap. I already tested it on a windows machine.

**Comment by cavearr** [comment]
Here it is! https://github.com/FPGAwars/tools-graphviz

 I have created the skeleton for you, I prefer that you upload it, you are the architect of this package and it is a great job, you should be the main contributor.

Thank you so much!

**Comment by cavearr** [comment]
@zapta 🔥

**Comment by zapta** [comment]
Thanks Carlos!  Will do.

**Comment by zapta** [comment]
Release created. Closing.
