### ISSUE TITLE
How to use the flags ``--size``, ``--type``, ``--pack``?

### ISSUE THREAD

**Issue by zapta** [FPGAwars/apio#468]
@Obijuan, @cavearr,

if I type ``apio build --size 32k`` I get the error ``Error: Missing FPGA``, and If I add the ``--fpga`` flag I get the error ``Error: contradictory arguments: ('8k', '32k')``.  It's the same for apio prog (0.9.5) and the latest apio dev.

What am I missing?

The relevant code is here 
https://github.com/FPGAwars/apio/blob/17c70b0a1782435d55d82ed2a68d3af30f5c3795/apio/managers/arguments.py#L193

**Comment by cavearr** [comment]
Hi @zapta ! i'm out of home now, but check if you are using the right arguments for the new nextpnr or yosys.  In nexpnr now you need to pass por example --package hx8k , check if this is correct or we are using old toolchain arguments.

**Comment by cavearr** [comment]
Reviewing the code, could be the FPGA board selected in the config is not set? as soon as i arrive i'll check it.

**Comment by zapta** [comment]
The error happens long before yosys or nextpnr, in the apio process itself, before scons.

The parsing is done in these steps
1. The arguments (e.g. 'size') are populated in the config dictionary.
2. The code asserts that the argument 'fpga' is in the dictionary
3. The code tries to populate the 'size' value from the fpga definition (originated at fpgas.json) and complains if a different 'size' value is ready in the dictionary.

I don't see how the flags --size  --type --pack flags can be used, and I presume that icestudio doesn't use them.

**Comment by cavearr** [comment]
i think the --size is used for example for boards that could have different FPGA chips, for example the same board with ice40  fpga but could exists with size 4k or 8k but not exists ice40 of 32k.

If you build for a board with an ice40 fpga configured and specify 32k appears the error "contradictory".

In the same way you can't specify size without specify fpga model.

And pack is needed for nexpnr (i don't deep in apio but i understood that apio needs to specify the packaging of the fpga chip to nextpnr)

**Comment by zapta** [comment]
@cavearr, can you give an example of a useful ``apio build`` command with ``--size``, ``--type`` or ``--pack``?

**Comment by cavearr** [comment]
At Icestudio i don't use it, the only use is "--package"  that i don't know if is the same as "--pack" for exapmple:   nextpnr-ice40 --hx8k --package tq144:4k --json hardware.json --asc hardware.asc --report hardware.pnr --pcf main.pcf -q

Are you sure we could delete this commands? there are a lot of boards and i don't know if there are neccesary for some of theme.

**Comment by zapta** [comment]
FPGA ``iCE40-HX1K-TQ144`` already has its ``pack  = tq144`` in fpgas.json and therefore the ``--pack tq144`` doesn't do anything. Same for ``--size 1k``.  


fpgas.json
```
  "iCE40-HX1K-TQ144": {
    "arch": "ice40",
    "type": "hx",
    "size": "1k",
    "pack": "tq144"
  },
```

In other words, these two commands are identical:

```
apio build --fpga iCE40-HX1K-TQ144 --pack tq144 --size 1k

apio build --fpga iCE40-HX1K-TQ144
```


Here is a test that demonstrates that the two commands result with the same nextpnr command

```
/Users/user/projects/apio_dev/repo/test-examples/Alhambra-II/02-jumping-LED $ mv apio.ini apio.ini.keep

/Users/user/projects/apio_dev/repo/test-examples/Alhambra-II/02-jumping-LED $ rm hardware.*

/Users/user/projects/apio_dev/repo/test-examples/Alhambra-II/02-jumping-LED $ apio build --fpga iCE40-HX1K-TQ144 --pack tq144 --size 1k
Info: No apio.ini file
[Tue Nov 19 13:11:57 2024] Processing custom board
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
yosys -p "synth_ice40 -top main -json hardware.json" -q main.v
Warning: wire '\q' is assigned in a block at main.v:3171.14-3171.21.
Warning: wire '\q' is assigned in a block at main.v:3175.6-3175.12.
nextpnr-ice40 --hx1k --package tq144 --json hardware.json --asc hardware.asc --pcf main.pcf -q
icepack hardware.asc hardware.bin
=============================================================================== [SUCCESS] Took 1.75 seconds ===============================================================================


/Users/user/projects/apio_dev/repo/test-examples/Alhambra-II/02-jumping-LED $ rm hardware.*
/Users/user/projects/apio_dev/repo/test-examples/Alhambra-II/02-jumping-LED $ apio build --fpga iCE40-HX1K-TQ144 
Info: No apio.ini file
[Tue Nov 19 13:12:08 2024] Processing custom board
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
yosys -p "synth_ice40 -top main -json hardware.json" -q main.v
Warning: wire '\q' is assigned in a block at main.v:3171.14-3171.21.
Warning: wire '\q' is assigned in a block at main.v:3175.6-3175.12.
nextpnr-ice40 --hx1k --package tq144 --json hardware.json --asc hardware.asc --pcf main.pcf -q
icepack hardware.asc hardware.bin
=============================================================================== [SUCCESS] Took 1.75 seconds ===============================================================================
```

I still can't see how these three flags are useful, considering that we don't allow them to override values in fpgas.json.

Regarding the deletion, these flags where planned to deletion anyway since the new apio allows users to use a custom fpgas.json in their project directory (an idea borrowed from platformio) in case they want to use a new fpga or to override arch, size, type, or pack.  

Does this make sense?

**Comment by cavearr** [comment]
@zapta Sorry! I didn't understand you! I thought you were talking about arguments or configurations as a concept, not just the argument.

If this is present in celery.ini and the new policy is to remove it from the argument list... I'm all for removing it!

**Comment by zapta** [comment]
Thanks Carlos.

BTW, what is the status of this ?
https://github.com/FPGAwars/apio/issues/453

**Comment by cavearr** [comment]
I am migrating icestudio to the new system, I have little left, it will take about a week to have it up and running.
