### ISSUE TITLE
Please update the release of apio-examples

### ISSUE THREAD

**Issue by zapta** [FPGAwars/apio#475]
Please create new release files for the apio 'examples' package. I need a latest version with pr https://github.com/FPGAwars/apio-examples/pull/26 for an integration test.  

With the current prod release, ColorLight-5A-75B-V8/Ledon doesn't fails apio lint and apio test.

You can do in in-place in the current version, bump the version and update VERSION, or bump the version and create VERSION_DEV that points to the new version.

**Comment by Obijuan** [comment]
Released as the 0.1.0 version
