### ISSUE TITLE
[For discussion] Is APIO_PACKAGES_DIR (or APIO_PKG_DIR) needed?

### ISSUE THREAD

**Issue by zapta** [FPGAwars/apio#499]
Currently apio dev support the env variables ``APIO_HOME_DIR`` and ``APIO_PACKAGES_DIR``.  Is ``APIO_PACKAGES_DIR`` used anywhere?  Can I simply have it hard wired to ``$APIO_HOME_DIR/packages``?  

Motivation is code and test simplicity.

@Obijuan, @cavearr, any thoughts?

**Comment by cavearr** [comment]
Sorry @zapta but i don't have the deep knowledge in apio to decide if this envs could be reduced.

**Comment by zapta** [comment]
@cavearr, you don't use in in icestudio, right?  I see only reference to APIO_HOME_DIR.

**Comment by Obijuan** [comment]
> Currently apio dev support the env variables APIO_HOME_DIR and APIO_PACKAGES_DIR. Is APIO_PACKAGES_DIR used anywhere? Can I simply have it hard wired to $APIO_HOME_DIR/packages?
Yes, you can

**Comment by cavearr** [comment]
no i don't use it 


De: "Zapta" ***@***.***> 
Para: "FPGAwars" ***@***.***> 
CC: "Carlos" ***@***.***>, "Mention" ***@***.***> 
Enviados: Martes, 17 de Diciembre 2024 23:08:33 
Asunto: Re: [FPGAwars/apio] [For discussion] Is APIO_PACKAGES_DIR (or APIO_PKG_DIR) needed? (Issue #499) 





[ https://github.com/cavearr | @cavearr ] , you don't use in in icestudio, right? I see only reference to APIO_HOME_DIR.

**Comment by zapta** [comment]
Thanks. Will delete it now. Closing.
