### ISSUE TITLE
[Feature] New apio scons command

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#65]
The apio init command generates the SConstruct, so that the user can change/modify it

For multiboard support, it is better to use the init comand for creating a new project, the same as platformio do:

apio init --board icestick

For that reason, the current apio init behaviour should be moved to apio scons:

apio scons    --> It will generate the default SConstruct file
apio init --> It will create the apio.ini file, with the project configuration: board, name, and so on...

**Comment by Jesus89** [comment]
Good point!

**Comment by Obijuan** [comment]
Done!

Now the init command is available for implementing the multiboard support
