### ISSUE TITLE
[Feature] Implement funny ASCII graphics messages :-)

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#66]
```
   _____                             _ 
  / ____|                           | |
 | (___  _   _  ___ ___ ___  ___ ___| |
  \___ \| | | |/ __/ __/ _ \/ __/ __| |
  ____) | |_| | (_| (_|  __/\__ \__ \_|
 |_____/ \__,_|\___\___\___||___/___(_)
```                                       

We can use some of this funny ASCII messages in apio. 
In this link there is a wonderful tool for converting text into ASCII art:

http://patorjk.com/software/taag/#p=display&f=Big&t=Success!

The priority of this issue is very low... but it can be fun :-)

**Comment by Jesus89** [comment]
Done: 7f62cef0c0a0a30a185d2684a21a72289360486d

To enable, just edit the if flag.
