### ISSUE TITLE
[Feature] Include the option --sayno to the apio examples command

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#90]
If during the copying of the examples files there exist a file with the same name, apio ask the user if it can overwrite that file.

With the opcion --sayno the answer is always no, and no questions are asked.  This is needed in apio-ide. In apio-ide we do not want the apio back-end to ask questions on the console

**Comment by Jesus89** [comment]
I suggest to add - y to yeas to all and - n to no to all

**Comment by Obijuan** [comment]
Done!
I've implemented the -n option by now
